sudo: required
services:
  - docker

before_install:
  - docker build -t izhal/docker-react -f Dockerfile.dev .

scripts:
  - docker run izhal/docker-react npm run coverage

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: docker-reactjs
  on:
    branch: master
